burger=document.querySelector('.burger');
navbar=document.querySelector('.navbar');
rightnav=document.querySelector('.rightnav');
navList=document.querySelector('.nav-list');
burger.addEventListener('click',()=>{
        rightnav.cc.toggle('v-class-rep');
        navList.cc.toggle('v-class-rep');
        navbar.cc.toggle('h-nav-rep');
})